"""create control plane tables

Revision ID: 00d5c519db84
Revises: 
Create Date: 2026-08-15 13:18:02.730062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00d5c519db84'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_code_batches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('uses_per_code', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('access_policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('per_source_hour_limit', sa.Integer(), nullable=True),
    sa.Column('global_daily_limit', sa.Integer(), nullable=True),
    sa.Column('concurrent_analysis_limit', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('admin_subject', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('details_json', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_audit_events_action'), 'admin_audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_admin_audit_events_admin_subject'), 'admin_audit_events', ['admin_subject'], unique=False)
    op.create_index(op.f('ix_admin_audit_events_occurred_at'), 'admin_audit_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_admin_audit_events_resource_type'), 'admin_audit_events', ['resource_type'], unique=False)
    op.create_table('admin_users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('access_codes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('prefix', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('uses_total', sa.Integer(), nullable=False),
    sa.Column('uses_consumed', sa.Integer(), nullable=False),
    sa.Column('uses_reserved', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['access_code_batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_hash')
    )
    op.create_index(op.f('ix_access_codes_batch_id'), 'access_codes', ['batch_id'], unique=False)
    op.create_table('admin_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('admin_user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_admin_sessions_admin_user_id'), 'admin_sessions', ['admin_user_id'], unique=False)
    op.create_table('usage_reservations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('access_code_id', sa.Uuid(), nullable=True),
    sa.Column('idempotency_hash', sa.String(length=64), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('release_reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['access_code_id'], ['access_codes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_id'),
    sa.UniqueConstraint('idempotency_hash')
    )
    op.create_index(op.f('ix_usage_reservations_access_code_id'), 'usage_reservations', ['access_code_id'], unique=False)
    op.create_table('access_code_usage_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reservation_id', sa.Uuid(), nullable=True),
    sa.Column('code_id', sa.Uuid(), nullable=False),
    sa.Column('analysis_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['code_id'], ['access_codes.id'], ),
    sa.ForeignKeyConstraint(['reservation_id'], ['usage_reservations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_code_usage_events_analysis_id'), 'access_code_usage_events', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_access_code_usage_events_code_id'), 'access_code_usage_events', ['code_id'], unique=False)
    op.create_index(op.f('ix_access_code_usage_events_reservation_id'), 'access_code_usage_events', ['reservation_id'], unique=False)
    op.create_table('analysis_runs',
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('api_version', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('media_type', sa.String(length=64), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('shooting_intent', sa.Text(), nullable=True),
    sa.Column('report_json', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('planner_prompt_version', sa.String(length=64), nullable=True),
    sa.Column('knowledge_source_id', sa.String(length=128), nullable=True),
    sa.Column('knowledge_source_version', sa.String(length=64), nullable=True),
    sa.Column('embedding_model', sa.String(length=128), nullable=True),
    sa.Column('reranker_model', sa.String(length=128), nullable=True),
    sa.Column('retrieved_chunk_ids_json', sa.Text(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('sanitized_diagnostic', sa.Text(), nullable=True),
    sa.Column('access_code_id', sa.Uuid(), nullable=True),
    sa.Column('reservation_id', sa.Uuid(), nullable=True),
    sa.Column('feedback_token_hash', sa.String(length=64), nullable=True),
    sa.Column('report_retained_until', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['access_code_id'], ['access_codes.id'], ),
    sa.ForeignKeyConstraint(['reservation_id'], ['usage_reservations.id'], ),
    sa.PrimaryKeyConstraint('analysis_id')
    )
    op.create_index(op.f('ix_analysis_runs_started_at'), 'analysis_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_analysis_runs_status'), 'analysis_runs', ['status'], unique=False)
    op.create_table('dimension_ratings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('target', sa.String(length=40), nullable=False),
    sa.Column('vote', sa.String(length=8), nullable=False),
    sa.Column('reason_codes_json', sa.Text(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_runs.analysis_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_id', 'target', name='uq_dimension_ratings_analysis_target')
    )
    op.create_index(op.f('ix_dimension_ratings_analysis_id'), 'dimension_ratings', ['analysis_id'], unique=False)
    op.create_table('problem_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_id', sa.Uuid(), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('tags_json', sa.Text(), nullable=False),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('runtime_metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_runs.analysis_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problem_reports_analysis_id'), 'problem_reports', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_problem_reports_created_at'), 'problem_reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_problem_reports_status'), 'problem_reports', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_problem_reports_status'), table_name='problem_reports')
    op.drop_index(op.f('ix_problem_reports_created_at'), table_name='problem_reports')
    op.drop_index(op.f('ix_problem_reports_analysis_id'), table_name='problem_reports')
    op.drop_table('problem_reports')
    op.drop_index(op.f('ix_dimension_ratings_analysis_id'), table_name='dimension_ratings')
    op.drop_table('dimension_ratings')
    op.drop_index(op.f('ix_analysis_runs_status'), table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_started_at'), table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_index(op.f('ix_access_code_usage_events_reservation_id'), table_name='access_code_usage_events')
    op.drop_index(op.f('ix_access_code_usage_events_code_id'), table_name='access_code_usage_events')
    op.drop_index(op.f('ix_access_code_usage_events_analysis_id'), table_name='access_code_usage_events')
    op.drop_table('access_code_usage_events')
    op.drop_index(op.f('ix_usage_reservations_access_code_id'), table_name='usage_reservations')
    op.drop_table('usage_reservations')
    op.drop_index(op.f('ix_admin_sessions_admin_user_id'), table_name='admin_sessions')
    op.drop_table('admin_sessions')
    op.drop_index(op.f('ix_access_codes_batch_id'), table_name='access_codes')
    op.drop_table('access_codes')
    op.drop_table('admin_users')
    op.drop_index(op.f('ix_admin_audit_events_resource_type'), table_name='admin_audit_events')
    op.drop_index(op.f('ix_admin_audit_events_occurred_at'), table_name='admin_audit_events')
    op.drop_index(op.f('ix_admin_audit_events_admin_subject'), table_name='admin_audit_events')
    op.drop_index(op.f('ix_admin_audit_events_action'), table_name='admin_audit_events')
    op.drop_table('admin_audit_events')
    op.drop_table('access_policy')
    op.drop_table('access_code_batches')
    # ### end Alembic commands ###
