"""drop unused reservation request hash

Revision ID: 908ec3482c8d
Revises: 00d5c519db84
Create Date: 2026-08-15 13:24:22.491473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '908ec3482c8d'
down_revision: Union[str, None] = '00d5c519db84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usage_reservations', 'request_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage_reservations', sa.Column('request_hash', sa.VARCHAR(length=64), nullable=False))
    # ### end Alembic commands ###
