"""re-add reservation request hash

Revision ID: ffa62323f640
Revises: 908ec3482c8d
Create Date: 2026-08-15 13:40:32.667659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffa62323f640'
down_revision: Union[str, None] = '908ec3482c8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'usage_reservations',
        sa.Column(
            'request_hash',
            sa.String(length=64),
            nullable=False,
            server_default='legacy',
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usage_reservations', 'request_hash')
    # ### end Alembic commands ###
